[package]
name = "escposify"
version = "0.1.3"
description = "A ESC/POS driver for Rust"
readme = "README.md"
keywords = ["ESC", "POS", "printer", "driver"]
repository = "https://github.com/local-group/rust-escposify"
documentation = "http://dl.ahorn.me/rust-doc/escposify/escposify/"
license = "MIT"
authors = ["Qian Linfeng <thewawar@gmail.com>"]


[dependencies]
encoding = "0.2.32"
byteorder = "0.5.1"
image = "0.12"
qrcode = "0.1.7"

[dev-dependencies]
tempfile = "2.1.3"
